# Site settings
title: Sentiment Clusters
email: tstirrat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An approach to analyzing the content and sentiments of tweets
  through natural language processing and network theory.
baseurl: "/sentimentClusters" # the subpath of your site, e.g. /blog/
url: "https://tstirrat15.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Used for Navigation Links.
# Needs to be updated every time there's a new page added.
navigation:
- text: Abstract
  title: Abstract
  url: /abstract/
- text: Data Collection
  url: /data_collection/
  title: Data Collection
- text: Munging
  title: Munging
  url: /munging/
- text: Finding Communities
  title: Finding Communities
  url: /finding_communities/
- text: Analysis
  title: Analysis
  url: /analysis/
- text: Conclusions
  title: Conclusions
  url: /conclusions/

# Make it so that pages are included
include: ['_pages']