# Site settings
title: Sentiment Clusters
email: tstirrat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Used for Navigation Links.
# Needs to be updated every time there's a new page added.
navigation:
- text: Abstract
  title: Abstract
  url: /_pages/abstract.html
- text: Data Collection
  url: /_pages/data_collection.html
  title: Data Collection
- text: Munging
  title: Munging
  url: /_pages/munging.html
- text: Finding Communities
  title: Finding Communities
  url: /_pages/finding_communities.html
- text: Analysis
  title: Analysis
  url: /_pages/analysis.html
- text: Conclusions
  title: Conclusions
  url: /_pages/conclusions.html